front_end: "https://spring-time-tracker.herokuapp.com"
invite_expry: 1
half_day: 0.5
all_day: 1
mail_max_length: 255
password_min_length: 6
domain_min_length: 3
domain_max_length: 20
send_later: 2
role_min_length: 2
host: 'https://timecloudbackend.herokuapp.com'
# host: 'https://pdk-timecloud.herokuapp.com'
